# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scrapy_grpc.pb import scrapy_grpc_pb2 as scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scrapy_grpc/pb/scrapy_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrawlerStub:
    """Control and inspect a running Scrapy crawler.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/scrapy_grpc.Crawler/GetStatus',
                request_serializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatusRequest.SerializeToString,
                response_deserializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/scrapy_grpc.Crawler/GetStats',
                request_serializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatsRequest.SerializeToString,
                response_deserializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.StopCrawler = channel.unary_unary(
                '/scrapy_grpc.Crawler/StopCrawler',
                request_serializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StopRequest.SerializeToString,
                response_deserializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StopResponse.FromString,
                _registered_method=True)


class CrawlerServicer:
    """Control and inspect a running Scrapy crawler.
    """

    def GetStatus(self, request, context):
        """Report which spider is running and how many items it has scraped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Return a snapshot of the crawler's stats collector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCrawler(self, request, context):
        """Ask the crawler to shut down gracefully.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatusRequest.FromString,
                    response_serializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatusResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatsRequest.FromString,
                    response_serializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatsResponse.SerializeToString,
            ),
            'StopCrawler': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCrawler,
                    request_deserializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StopRequest.FromString,
                    response_serializer=scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapy_grpc.Crawler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapy_grpc.Crawler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Crawler:
    """Control and inspect a running Scrapy crawler.
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapy_grpc.Crawler/GetStatus',
            scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatusRequest.SerializeToString,
            scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapy_grpc.Crawler/GetStats',
            scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatsRequest.SerializeToString,
            scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCrawler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapy_grpc.Crawler/StopCrawler',
            scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StopRequest.SerializeToString,
            scrapy__grpc_dot_pb_dot_scrapy__grpc__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
