# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scrapy_grpc/pb/scrapy_grpc.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'scrapy_grpc/pb/scrapy_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n scrapy_grpc/pb/scrapy_grpc.proto\x12\x0bscrapy_grpc\"\x0f\n\rStatusRequest\"H\n\x0eStatusResponse\x12\x0e\n\x06spider\x18\x01 \x01(\t\x12\x0f\n\x07running\x18\x02 \x01(\x08\x12\x15\n\ritems_scraped\x18\x03 \x01(\x03\"\x0e\n\x0cStatsRequest\"s\n\rStatsResponse\x12\x34\n\x05stats\x18\x01 \x03(\x0b\x32%.scrapy_grpc.StatsResponse.StatsEntry\x1a,\n\nStatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\r\n\x0bStopRequest\" \n\x0cStopResponse\x12\x10\n\x08stopping\x18\x01 \x01(\x08\x32\xd6\x01\n\x07\x43rawler\x12\x44\n\tGetStatus\x12\x1a.scrapy_grpc.StatusRequest\x1a\x1b.scrapy_grpc.StatusResponse\x12\x41\n\x08GetStats\x12\x19.scrapy_grpc.StatsRequest\x1a\x1a.scrapy_grpc.StatsResponse\x12\x42\n\x0bStopCrawler\x12\x18.scrapy_grpc.StopRequest\x1a\x19.scrapy_grpc.StopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scrapy_grpc.pb.scrapy_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSRESPONSE_STATSENTRY']._loaded_options = None
  _globals['_STATSRESPONSE_STATSENTRY']._serialized_options = b'8\001'
  _globals['_STATUSREQUEST']._serialized_start=49
  _globals['_STATUSREQUEST']._serialized_end=64
  _globals['_STATUSRESPONSE']._serialized_start=66
  _globals['_STATUSRESPONSE']._serialized_end=138
  _globals['_STATSREQUEST']._serialized_start=140
  _globals['_STATSREQUEST']._serialized_end=154
  _globals['_STATSRESPONSE']._serialized_start=156
  _globals['_STATSRESPONSE']._serialized_end=271
  _globals['_STATSRESPONSE_STATSENTRY']._serialized_start=227
  _globals['_STATSRESPONSE_STATSENTRY']._serialized_end=271
  _globals['_STOPREQUEST']._serialized_start=273
  _globals['_STOPREQUEST']._serialized_end=286
  _globals['_STOPRESPONSE']._serialized_start=288
  _globals['_STOPRESPONSE']._serialized_end=320
  _globals['_CRAWLER']._serialized_start=323
  _globals['_CRAWLER']._serialized_end=537
# @@protoc_insertion_point(module_scope)
